version: '3'
services:
  app:
    build: .
    environment:
      VIRTUAL_HOST: jichoup.com
      VIRTUAL_PORT: 9000
  nginx-proxy:
    image: jwilder/nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./public:/usr/share/nginx/html:ro"
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
volumes_from:
  - nginx
